<div class="list-brands t-carousel">
    <h1>All the best Brands</h1>
    <ul id="owl-demo" class="owl-carousel owl-theme">
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Cigweld_B-W_192x125.jpg" alt="Cigweld">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Dewalt_BW_192x125.jpg" alt="Dewalt">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Bosch_B-W_192x125.jpg" alt="Bosch">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Festool_BW_192x125.jpg" alt="Festool">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Cigweld_B-W_192x125.jpg" alt="Cigweld">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Husqvarna.jpg" alt="Husqvarna">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Cigweld_B-W_192x125.jpg" alt="Cigweld">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Milwaukee_BW_192x125.jpg" alt="Milwaukee">
            </a>
        </li>
    </ul>

    <ul class="brandlist-mobile" >
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Cigweld_B-W_192x125.jpg" alt="Cigweld">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Dewalt_BW_192x125.jpg" alt="Dewalt">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Bosch_B-W_192x125.jpg" alt="Bosch">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Festool_BW_192x125.jpg" alt="Festool">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Cigweld_B-W_192x125.jpg" alt="Cigweld">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Husqvarna.jpg" alt="Husqvarna">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Cigweld_B-W_192x125.jpg" alt="Cigweld">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Milwaukee_BW_192x125.jpg" alt="Milwaukee">
            </a>
        </li>
        <!--            <div class="owl-prev">prev</div>-->
    </ul>


</div>

<script type="text/javascript">
    $j = jQuery.noConflict();
    $j('#owl-demo').owlCarousel({
        loop:true,
        margin:10,
        nav:true,
        dots: false,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:3
            },
            1000:{
                items:5
            }
        }
    })
</script>
