
<?php 
    //todo: move logic to the block
    list($min,$max) = $this->_filter->getMinMaxPriceInt(); 
    list($from,$to) = explode(',', $this->_filter->getActiveState()); 
    
     $from = floor(max($from, $min));
    
    if ($to) {
         $to   = ceil(min($to, $max));
    } else {
         $to = $max;
    }
    
    if ($to<1 && $from<1) {
         $to = $max;
    }

	//Set the slider width
    $width = 170;
    
    if ($max) {
        if ($max == $min) {
            $firstOffset = 0;
            $secondOffset = $width;
        } else  {
			 $firstOffset  = ($from-$min)*$width/($max-$min);
			 $secondOffset = ($to-$min)*$width/($max-$min);
        }
    } else  {
			$firstOffset  = 0;
			$secondOffset = 0;
    }
?>
<ol style="padding: 0px 15px;">
    <li class="price-container">
    <?php if ($to != $from) :?>
        <div style="padding: 10px 0px; margin-bottom: 15px;">
            <div id="fme_layered_price_slider<?php echo $this->_filter->getRequestVar()?>" class="price_slider">
                <div class="handle selected" style="left:<?php echo $firstOffset?>px"></div>
                <div class="handle" style="left:<?php echo $secondOffset?>px"></div>
            </div>
        </div>
    <?php endif;?> 

    <?php if ($to != $from) :?> 
    <div class="form-price-slider">
        <div style="float: left;">
            <?php echo $this->getSymbol()?> <input type="text" size="1" class="slider-number" id="price_range_from<?php echo $this->_filter->getRequestVar()?>" value="<?php echo $from?>">
        </div>
        
        <div style="float: right;">
            <?php echo $this->getSymbol()?> <input type="text" size="1" class="slider-number" id="price_range_to<?php echo $this->_filter->getRequestVar()?>" value="<?php echo $to?>">
        </div>
    </div>
    <div style="clear: both;"></div>
    
    <div style="text-align: center; padding-top: 20px;">
        <p style="font-size: 15px;">Drag to indicate price range</p>
    </div>
    
    <script type="text/javascript">
        var slider = create_price_slider(<?php echo $width.', '.$firstOffset.', '.$secondOffset.', '.$min.', '.$max.',"'.$this->_filter->getRequestVar()?>");
    </script>

    <?php else:?>
        <?php echo $this->__('Value:')?> 
        <?php echo $this->getSymbol()?><span id="price_range_from<?php echo $this->_filter->getRequestVar()?>"><?php echo $from?></span>
    <?php endif;?> 
    </li>
</ol>