

<html>
<div style=" width: 100%;
    padding: 0 20px 0 20px;
    margin: 0 33px 0 33px;
    height: 537px;
    background: url('https://www.totaltools.com.au/static/version1498091224/frontend/Totaltools/base/en_AU/images/hammer.jpg') no-repeat right;
" class="404-page">
    <div style=" font-family: 'my font 3';
    font-style: normal;
    font-weight: 400;
    line-height: 1.25;
    font-size: 1.6rem;
    color: #333;" class="404-page-title-wrapper">
        <h1 style="font-family: 'my font';
        color: #333;
        margin-bottom:40px;
        " class="404-page-title"><span>OPPS! WE CAN'T SEEM TO FIND THE PAGE YOU LOOKING FOR </span></h1>
    </div>
    <div class="404-page-columns">
        <div class="404-page-columns-main">
            <p style=" margin-bottom: 25px;"><strong>Error code: 404</strong></p>
            <p style=" margin-bottom: 25px;">Here are some helpful links instead:</p>
            <ul>
                <li style="margin-bottom: 10px;"><a style=" color: #294d98;
    text-decoration: none;
    font-family: 'my font 3';" href="/">Home</a> </li>
                <li style="margin-bottom: 10px;"><a style=" color: #294d98;
    text-decoration: none;
    font-family: 'my font 3';" href="#">Login/Create Account</a></li>
                <li style="margin-bottom: 10px;"><a style=" color: #294d98;
    text-decoration: none;
    font-family: 'my font 3';" href="#">Franchise Opportunities</a></li>
                <li style="margin-bottom: 10px;"><a style=" color: #294d98;
    text-decoration: none;
    font-family: 'my font 3';" href="#">About Us</a></li>
                <li style="margin-bottom: 10px;"><a style=" color: #294d98;
    text-decoration: none;
    font-family: 'my font 3';" href="#">FAQ's</a></li>
            </ul>
        </div>
    </div>
</div>
</html>
