<div class="banner1 banner4 row">
    <div class="col-md-3 col-sm-3 banner-item">

        <a href="#">
            <img alt="Combo Kits"  class="categorylanding-box-image" src="media/wysiwyg/Screenshot from 2017-07-07 15-59-38.png">
        </a>
    </div>
    <div class="col-md-3 col-sm-3 banner-item">
        <a href="#">
            <img alt="Combo Kits"  class="categorylanding-box-image" src="media/wysiwyg/Screenshot from 2017-07-07 15-59-38.png">
        </a>
    </div>
    <div class="col-md-3 col-sm-3 banner-item">
        <a href="#">

            <img alt="Combo Kits"  class="categorylanding-box-image" src="media/wysiwyg/Screenshot from 2017-07-07 15-59-38.png">
        </a>
    </div>
    <div class="col-md-3 col-sm-3 banner-item">
        <a href="#">

            <img alt="Combo Kits"  class="categorylanding-box-image" src="media/wysiwyg/Screenshot from 2017-07-07 15-59-38.png">
        </a>
    </div>
</div>