<div class="banner1 banner2 row">
    <div class="col-md-9 col-xs-12">

        <a href="#">
            <div class="categorylanding-box ">
                <div class="categorylanding-box-container">


                    <h2 class="categorylanding-box-heading">Drills</h2>

                    <div class="categorylanding-box-content std">
                        <p>Buying a cordless tool kit from Total Tools is the best value way to build up your collection.</p>
                    </div>
                    <button class="button button3 "><span><span>Shop Drills</span></span></button>

                </div>
                <img alt="Combo Kits"  class="categorylanding-box-image categorylanding-box-image-desktop" src="media/wysiwyg/Screenshot from 2017-07-07 14-42-26.png">
                <img alt="Combo Kits"  class="categorylanding-box-image categorylanding-box-image-mobile" src="media/wysiwyg/Screenshot from 2017-07-11 15-56-40.png">

            </div>
        </a>
    </div>
    <div class="col-md-3 col-xs-12 landing-banner2-3">
        <a href="#">
            <div class="categorylanding-box ">
                <div class="categorylanding-box-container">
                    <h2 class="categorylanding-box-heading">Grinders</h2>

                    <button class="button button3"><span><span>Shop drills</span></span></button>
                </div>
                <img alt="Combo Kits"  class="categorylanding-box-image" src="media/wysiwyg/Screenshot from 2017-07-07 14-57-29.png">

            </div>
        </a>
    </div>
</div>