<div class="banner1 row">
    <div class="col-md-6 col-sm-6  banner1-item">
        <a href="#">
            <div class="categorylanding-box block1-landing">
                <div class="categorylanding-box-container">
                    <h2 class="categorylanding-box-heading">Combo Kits</h2>

                    <div class="categorylanding-box-content std">
                        <p>Buying a cordless tool kit from Total Tools is the best value way to build up your collection.</p>
                    </div>
                    <button class="button categorylanding-box-button"><span><span>Shop Now</span></span></button>
                </div>
                <img alt="Combo Kits"  class="categorylanding-box-image" src="media/wysiwyg/pos_2_488x260_pt_combos_1.jpg">

            </div>
        </a>
    </div>
    <div class="col-md-6 col-sm-6 banner1-item">
        <a href="#">
            <div class="categorylanding-box block1-landing">
                <div class="categorylanding-box-container">
                    <h2 class="categorylanding-box-heading">Combo Kits</h2>

                    <div class="categorylanding-box-content std">
                        <p>Buying a cordless tool kit from Total Tools is the best value way to build up your collection.</p>
                    </div>
                    <button class="button categorylanding-box-button"><span><span>Shop Now</span></span></button>
                </div>
                <img alt="Combo Kits"  class="categorylanding-box-image" src="media/wysiwyg/pos_2_488x260_pt_combos_1.jpg">

            </div>
        </a>
    </div>
</div>