<div class="banner1 banner3 row">
    <div class="col-md-4 col-sm-4 ">

        <a href="#">
            <img alt="Combo Kits"  class="categorylanding-box-image" src="media/wysiwyg/Screenshot from 2017-07-07 15-37-49.png">
        </a>
    </div>
    <div class="col-md-4 col-sm-4 ">
        <a href="#">
            <img alt="Combo Kits"  class="categorylanding-box-image" src="media/wysiwyg/Screenshot from 2017-07-07 15-37-49.png">
        </a>
    </div>
    <div class="col-md-4 col-sm-4 ">
        <a href="#">

            <img alt="Combo Kits"  class="categorylanding-box-image" src="media/wysiwyg/Screenshot from 2017-07-07 15-37-49.png">
        </a>
    </div>
</div>