 <section class="home-block3">
    <div class="page-main">
        <h2>EVERY TOOL, EVERY TRADE</h2>
        <p>Total Tools have been passionately servicing Australia for more than 30 years. We stock the widest range of the world's biggest professional tool brands, with the newest tools always available online and in store. With access to over 60,000 products nationwide at 60 store locations, we can find the right tool for you. Our experienced and knowledge staff are happy to offer professional advice and service, which along with our Insiders loyalty scheme sets us apart from our competition.&nbsp;</p>

            <span class="action-learnmore" style="color: #ffffff;">
                <a href="#" target="_self">
                    <span style="color: #ffffff;">Learn more</span>
                </a>
            </span>

    </div>
</section>