 <section class="block4">
    <div class="page-main">
        <div class="row page-main">
            <div class="box-item left-box">
                <div class="row">
                    <div class="image-box">
                        <img class="image-bottom-homepage" src="media/wysiwyg/worker.png">
                    </div>

                    <div class="box-infor">
                    <div class="content-box">
                        <h2>FRANCHISE OPPORTUNITIES </h2>
                        <p>Do you aspire to be a business owner? Do you have retail experience or a trade background?</p>
                    </div>
                    <div class="button-box">
                        <a href="#" class="button"><span><span>Enquire Now</span></span></a>
                    </div>
                    </div>

                </div>
            </div>
            <div class="box-item right-box">
                <div class="row">
                    <div class="image-box">
                        <img class="image-bottom-homepage" src="media/wysiwyg/giftcard_iconog_1.png">
                    </div>
                    <div class="box-infor">
                    <div class="content-box">
                        <h2>gift cards available online!  </h2>
                        <p>Get a Gift Card Sent Direct To Your Door or Straight Into Your Inbox! </p>
                    </div>
                    <div class="button-box">
                        <a href="#" class="button"><span><span>Buy Now</span></span></a>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!--<section class="page-home-bottom bottom-boxes"><div class="page-main"><div class="box-item box1" style=""><div id="js__balance-box-home_bottom_left" class="balance-box balance-box-default balance-box-home_bottom_left  ">-->
<!---->
<!--                <div class="balance-box-container">-->
<!--                    <h2 class="balance-box-heading">-->
<!--                        FRANCHISE OPPORTUNITIES            </h2>-->
<!---->
<!--                    <div class="balance-box-content std">-->
<!--                        <p>Do you aspire to be a business owner? Do you have retail experience or a trade background?</p>            </div>-->
<!---->
<!--                    <a href="/franchising-enquiries" class="button balance-box-button">-->
<!--                <span><span>-->
<!--                    ENQUIRE NOW                </span></span>-->
<!--                    </a>-->
<!--                </div>-->
<!---->
<!--                <img alt="" data-desktop-image="https://www.totaltools.com.au/media/balance/box/image//w/o/worker.png" data-mobile-image="" class="balance-box-image" id="js__balance-box-img-home_bottom_left" src="https://www.totaltools.com.au/media/balance/box/image//w/o/worker.png">-->
<!---->
<!--            </div>-->
<!---->
<!--        </div><div class="box-item box2" style=""><div id="js__balance-box-home_bottom_right" class="balance-box balance-box-default balance-box-home_bottom_right  ">-->
<!---->
<!--                <div class="balance-box-container">-->
<!--                    <h2 class="balance-box-heading">-->
<!--                        gift cards available online!            </h2>-->
<!---->
<!--                    <div class="balance-box-content std">-->
<!--                        <p>Get a Gift Card Sent Direct To Your Door or Straight Into Your Inbox!&nbsp;</p>            </div>-->
<!---->
<!--                    <a href="/gift-cards" class="button balance-box-button">-->
<!--                <span><span>-->
<!--                    BUY NOW                </span></span>-->
<!--                    </a>-->
<!--                </div>-->
<!---->
<!--                <img alt="" data-desktop-image="https://www.totaltools.com.au/media/balance/box/image//g/i/giftcard_iconog_1.png" data-mobile-image="" class="balance-box-image" id="js__balance-box-img-home_bottom_right" src="https://www.totaltools.com.au/media/balance/box/image//g/i/giftcard_iconog_1.png">-->
<!---->
<!--            </div>-->
<!---->
<!--        </div></div>-->
<!--</section>-->