 <div id="block2-homepage" class="banner1">
    <div class="row page-main">
    <div class="col-md-4 col-sm-4 fist-child-block2">

        <a href="#">
            <div class="categorylanding-box ">
                <div class="categorylanding-box-container">


                    <h2 class="homepage-block-banner-title1"><span>Event update</span><br/> try the new range!</h2>

                    <button class="button categorylanding-box-button block2-banner-button1"><span><span>Register now</span></span></button>
<!--                    <img src="media/wysiwyg/Screenshot from 2017-07-12 14-07-54.png"/>-->
                </div>



            </div>
        </a>
    </div>
    <div class="col-md-4 col-sm-4">
        <a href="#">
            <div class="categorylanding-box ">
                <div class="categorylanding-box-container">
                    <h2 class="categorylanding-box-heading" style="width: 242px">
                        <span>Get the right tools</span>
                        <span class="sub-title">for the job</span>
                    </h2>

                    <button class="button categorylanding-box-button block2-banner-button2"><span><span>Shop now</span></span></button>
                </div>


            </div>
        </a>
    </div>
    <div class="col-md-4 col-sm-4">

        <a href="#">
            <div class="categorylanding-box ">
                <div class="categorylanding-box-container">


                    <h2 class="homepage-block-banner-title1"><span>Event update</span><br/> try the new range!</h2>

                    <button class="button categorylanding-box-button block2-banner-button1"><span><span>Register now</span></span></button>
                    <!--                    <img src="media/wysiwyg/Screenshot from 2017-07-12 14-07-54.png"/>-->
                </div>



            </div>
        </a>
    </div>
    </div>
</div>
