 <div id="homepage-slider" class="owl-carousel owl-theme">
    <div class="item">
        <a href="#">
            <div class="slide-box">
                <button class="button button3"><span>Shop Now</span></button>
                <img class="silder-img" src="https://www.totaltools.com.au/media/balance/box/image//r/o/rotobroach_hp-banner-web_1243x421_1.jpg">
            </div>
        </a>
    </div>
    <div class="item">
        <a href="#">
            <div class="slide-box">
                <button class="button button3"><span>Shop Now</span></button>
                <img class="silder-img" src="https://www.totaltools.com.au/media/balance/box/image//p/r/pricesweswearby_hp-banner-web_1243x421_2.jpg">
            </div>
        </a>
    </div>
    <div class="item">
        <a href="#">
            <div class="slide-box">
                <button class="button button3"><span>Shop Now</span></button>
                <img class="silder-img" src="https://www.totaltools.com.au/media/balance/box/image//b/o/bosch-getconnected_hp-banner-web_1243x421.jpg">
            </div>
        </a>
    </div>
    <div class="item">
        <a href="#">
            <div class="slide-box">
                <button class="button button3"><span>Shop Now</span></button>
                <img class="silder-img" src="https://www.totaltools.com.au/media/balance/box/image//m/a/makitaredemption_hp-banner-web_1243x421_1.jpg">
            </div>
        </a>
    </div>
    <div class="item">
        <a href="#">
            <div class="slide-box">
                <button class="button button3"><span>Shop Now</span></button>
                <img class="silder-img" src="https://www.totaltools.com.au/media/balance/box/image//e/v/evolution_hp-banner-web_1243x421.jpg">
            </div>
        </a>
    </div>
</div>

 <script type="text/javascript">
     $j = jQuery.noConflict();
     $j('#homepage-slider').owlCarousel({
         loop:true,
         margin:10,
         nav:false,
         dots: true,
         items: 1,
         autoplay: true
//         responsive:{
//             0:{
//                 items:1
//             },
//             600:{
//                 items:1
//             },
//             1000:{
//                 items:1
//             }
//         }
     })
 </script>

