 <section class="total-blog" id="home-total-blog">
    <div class="page-main">
        <div class="title-blog-section">
            <h1>Total Blog</h1>
            <p>
                If you're after the latest offers, promos, product releases and industry news, then our Total Tools Blog is your one stop destination. Need help deciding on which cordless drill to buy?
                You're not too sure if you require a Rotary Laser or Crossline Laser Level? Well you'll find the answers within our Total Tools Blog! So please, kick your feet up, relax and enjoy your stay.
            </p>
        </div>
        <div class="row list-home-blog">
            <div class="col-md-3 col-sm-3">
                <div class="thumbnail">
                    <a href="#">
                    <img alt="100%x200" data-src="holder.js/100%x200" style="height: 200px; width: 100%; display: block;" src="media/wysiwyg/Screenshot from 2017-07-13 11-57-03.png" data-holder-rendered="true">
                    </a>
                    <div class="caption">
                        <a href="#"><h3>Thumbnail label</h3></a>
                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                        <a href="#"><span>Read full article</span></a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-3">
                <div class="thumbnail">
                    <a href="#">
                        <img alt="100%x200" data-src="holder.js/100%x200" style="height: 200px; width: 100%; display: block;" src="media/wysiwyg/Screenshot from 2017-07-13 11-57-03.png" data-holder-rendered="true">
                    </a>
                    <div class="caption">
                        <a href="#"><h3>Thumbnail label</h3></a>
                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                        <a href="#"><span>Read full article</span></a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-3">
                <div class="thumbnail">
                    <a href="#">
                        <img alt="100%x200" data-src="holder.js/100%x200" style="height: 200px; width: 100%; display: block;" src="media/wysiwyg/Screenshot from 2017-07-13 11-57-03.png" data-holder-rendered="true">
                    </a>
                    <div class="caption">
                        <a href="#"><h3>Thumbnail label</h3></a>
                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                        <a href="#"><span>Read full article</span></a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-3">
                <div class="thumbnail">
                    <a href="#">
                        <img alt="100%x200" data-src="holder.js/100%x200" style="height: 200px; width: 100%; display: block;" src="media/wysiwyg/Screenshot from 2017-07-13 11-57-03.png" data-holder-rendered="true">
                    </a>
                    <div class="caption">
                        <a href="#"><h3>Thumbnail label</h3></a>
                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                        <a href="#"><span>Read full article</span></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="action-visit-blog">
            <button class="button button3"><span>Visit Our Blog</span></button>
        </div>
    </div>
</section>