<div class="container"> </div><!-- todo:for boostrap -->




<div id="Total-tools-header" class="Total-tools-page-header">

        <div class="Total-tools-page-header-part1">
            <div class="Total-tools-wrap-page-header-part1">
            <div class="my-header-divine">
                <div class="my-header-divine-child1">
                <ul class="my-contact-us-header" >
                    <li id="my-contact-us-header-1st">
<a href="/contactus">Contact Us</a>
                    </li>
                    <li>
<a href="#">Franchise Opportunities</a>
                    </li>
                </ul>
                    </div>
                <div class="my-header-divine-child2">
                    <div class="my-header-divine-child2-1">
                <div class="Total-tools-header-account-child"><b  style="border: none!important;"  class="Total-tools-welcome-msg"><?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getChildHtml('accountLinks') ?></b></div>
                   </div>




               <div class="my-header-divine-child2-2"
                <div id="Total-tools-header-account" class="Total-tools-skip-content">
                    <?php echo $this->getChildHtml('topLinks') ?></div>

              
                    </div>
                    </div>
            </div>
         </div>
            </div>

</div>






    <div  id="page-header-part2">
        <div id="wrap-page-header-part2">
            <div class="divine-dad">
              <div class="divine-child-1">
                   <div class="nav-for-moblie">
                  <i class="fa fa-bars" id="nav-symbol-moblie" aria-hidden="true"></i>
                       <div id="Total-tools-header-nav" class="Total-tools-skip-content">
                           <?php echo $this->getChildHtml('topMenu') ?>
                       </div>
                       </div>
                  <a class="Total-tools-logo-large" href="<?php echo $this->getUrl('') ?>">
                      <img class="img-responsive" src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="Total-tools-logo-large" /></a>
                  <a class="Total-tools-logo-small" class="Total-tools-logo" href="<?php echo $this->getUrl('') ?>">   <img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="Total-tools-logo-small" /></a>

                  <i  class="fa fa-search" id="search-symbol-for-mobile" aria-hidden="true"></i>







              </div>

            <div class="divine-child-2">

                    <div id="Total-tools-header-search" class="Total-tools-skip-content">
                        <?php echo $this->getChildHtml('topSearch') ?>


                </div>
                </div>
            <div class="divine-child-3">
                <div class="divine-2-1">
                    <i class="fa fa-map-marker" aria-hidden="true" id="location-symbol"></i>
                    <p id="location-text"><b>Store Location </b></p>
                    </div>




                <div class="divine-2-2">
                    <i class="fa fa-gift" id="gift-symbol" aria-hidden="true"></i>
                    <p id="gift-text"><b>Gift </b></p>
                    </div>

                  <div class="divine-2-3">

                    <div class="Total-tools-header-minicart">

                        <?php echo $this->getChildHtml('minicart_head'); ?>
                        </div>

                </div>
                </div>
                </div>
        </div>

        <div id="search-bar-for-mobile-only"></div>





    </div>
            <div class="page-header-part3">
                <div id="wrap-page-header-part3">
                <div id="Total-tools-header-nav" class="Total-tools-skip-content">
                    <?php echo $this->getChildHtml('topMenu') ?>
                    <div class="ms-submenu col-xs-12 sub_left" id="submenu-4" style="width: 1000px;   display:none;">
                        <div class="ms-content">
                            <div class="ms-maincontent" style="float:left;width:70%;">
                                <div class="row ms-category">
                                    <div class="col-category col-xs-4">
                                        <strong class="ms-boxtitle">Top Level Style</strong>
                                        <a class="form-group level1" href="#">Circular Saws</a>
                                        <a class="form-group level1" href="#">Cordless Combo Kits</a>
                                        <a class="form-group level1" href="#">Cordless Tools</a>
                                        <a class="form-group level2" href="#">Chargers</a>
                                        <a class="form-group level2" href="#">Batteries</a>
                                        <a class="form-group level2" href="#">Cordless Angle Grinders</a>
                                        <a class="form-group level2" href="#">Cordless Blowers</a>
                                        <a class="form-group level2" href="#">Cordless Circular Saws</a>
                                        <a class="form-group level2" href="#">Cordless Drills</a>

                                    </div>
                                    <div class="col-category col-xs-4">
                                        <strong class="ms-boxtitle">Top Level Style</strong>
                                        <a class="form-group level1" href="#">Drills</a>
                                        <a class="form-group level2" href="#">Bench/Pedestal</a>
                                        <a class="form-group level1" href="#">Grinders</a>
                                        <a class="form-group level2" href="#">Angle Grinders</a>
                                        <a class="form-group level2" href="#">Concrete Grinders</a>
                                        <a class="form-group level1" href="#">Impact Drivers &amp; Wrenches</a>
                                        <a class="form-group level1" href="#">Jobsite Radios</a>
                                        <a class="form-group level1" href="#">Mitre Saws</a>
                                        <a class="form-group level1" href="#">Multi Tools</a>

                                    </div>
                                    <div class="col-category col-xs-4">
                                        <strong class="ms-boxtitle">Top Level Style</strong>
                                        <a class="form-group level1" href="#">Polishers &amp; Sanders</a>
                                        <a class="form-group level2" href="#">Belt Sanders</a>
                                        <a class="form-group level2" href="#">Orbital Sanders</a>
                                        <a class="form-group level2" href="#">Palm Delta Sanders</a>
                                        <a class="form-group level1" href="#">Power Tool Accessories</a>
                                        <a class="form-group level2" href="#">Abrasives</a>
                                        <a class="form-group level2" href="#">Blades</a>
                                        <a class="form-group level2" href="#">Drilling</a>
                                        <a class="form-group level2" href="#">Fastener Drive</a>
                                        <a class="form-group level2" href="#">Hole Saws</a>
                                        <a class="form-group level2" href="#">Saw Stands &amp; Accessories</a>
                                        <a class="form-group level1" href="#">Routers</a>
                                        <a class="form-group level1" href="#">Saws</a>

                                    </div>
                                </div>
                            </div>
                            <div class="ms-featured" style="float:right;width:30%;">
                                <div class="row">
                                    <div class="col-sm-12 form-group">
                                        <strong class="ms-boxtitle">Featured Categories</strong>
                                    </div>
                                    <div class="f-category col-sm-12 col-xs-12 col-tn-12">
                                        <a class="product-image text-center form-group" href="https://www.totaltools.com.au/power-tools/cordless-combo-kits-2">
                                            <img title="Cordless Combo Kits" alt="Cordless Combo Kits" src="https://www.totaltools.com.au/media/catalog/category/PT_Combos.gif" width="110">
                                        </a>
                                        <a class="product-name form-group" href="#"><strong>Cordless Combo Kits</strong></a>
                                    </div>
                                    <div class="col-sm-12 form-group hidden-xs hidden-tn"></div>    <div class="f-category col-sm-12 col-xs-12 col-tn-12">
                                        <a class="product-image text-center form-group" href="https://www.totaltools.com.au/power-tools/drills">
                                            <img title="Drills" alt="Drills" src="https://www.totaltools.com.au/media/catalog/category/PT_Drills.gif" width="110">
                                        </a>
                                        <a class="product-name form-group" href="#"><strong>Drills</strong></a>
                                    </div>
                                    <div class="hidden-lg hidden-md hidden-sm hidden-xs col-tn-12"></div>    <div class="hidden-lg hidden-md hidden-sm col-xs-12 hidden-tn"></div>    <div class="col-sm-12 form-group hidden-xs hidden-tn"></div>    <div class="f-category col-sm-12 col-xs-12 col-tn-12">
                                        <a class="product-image text-center form-group" href="https://www.totaltools.com.au/power-tools/power-tool-accessories">
                                            <img title="Power Tool Accessories" alt="Power Tool Accessories" src="https://www.totaltools.com.au/media/catalog/category/PT_Accessories.gif" width="110">
                                        </a>
                                        <a class="product-name form-group" href="#"><strong>Power Tool Accessories</strong></a>
                                    </div>

                                    <div class="hidden-lg hidden-md hidden-sm hidden-xs col-tn-12"></div>    <div class="hidden-lg hidden-md hidden-sm col-xs-12 hidden-tn"></div>    <div class="col-sm-12 form-group hidden-xs hidden-tn"></div></div>
                            </div>
                        </div>
                        <div class="ms-footer"><p><strong >Featured  Brands</strong></p>
                            <ol>
                                <li class="grid12-5"><a href="#" target="_self"><img src="https://www.totaltools.com.au/media/wysiwyg/MegaMenu/Milwaukee_B-W_110x40.jpg" alt="milwaukee logo" width="110" height="40"></a></li>
                                <li class="grid12-5"><a href="#" target="_self"><img src="https://www.totaltools.com.au/media/wysiwyg/MegaMenu/Makita_B-W_110x40.jpg" alt="makita logo" width="110" height="40"></a></li>
                                <li class="grid12-5"><a href="#" target="_self"><img src="https://www.totaltools.com.au/media/wysiwyg/MegaMenu/Dewalt_B-W_110x40.jpg" alt="dewalt logo" width="110" height="40"></a></li>
                                <li class="grid12-5"><a href="#" target="_self"><img src="https://www.totaltools.com.au/media/wysiwyg/MegaMenu/Bosch_B-W_110x40.jpg" alt="bosch logo" width="110" height="40"></a></li>
                                <li class="grid12-5"><a href="#" target="_self"><img src="https://www.totaltools.com.au/media/wysiwyg/MegaMenu/Festool_B-W_110x40.jpg" alt="festool logo" width="110" height="40"></a></li>
                            </ol></div>
                    </div>

                </div>

                </div>
            </div>



            <div class="descoration">
                <div class="des-wrapper">
                <div class="row" id="des">
                    <div class="col-sm-4"><a href="#"><span><i id="check-box-icon" class="fa fa-check-square-o" aria-hidden="true"></i></span>  PRICES WE SWEAR BY WARRANTEED</a></div>
                    <div class="col-sm-3"><a href="#"><span><i id="calendar-icon" class="fa fa-calendar" aria-hidden="true"></i></span>   30 DAYS ONLINE RETURN</a></div>
                    <div class="col-sm-2"><a href="#"><span><i id="laptop-icon" class="fa fa-laptop" aria-hidden="true"></i></span>  FREE DELIVERY</a></div>
                    <div class="col-sm-3"><a href="#"><span><i id="global-icon" class="fa fa-globe" aria-hidden="true"></i></span>  62 STORE NATION WIDE</a></div>
                </div>
                </div>
            </div>


    </div>


    <?php echo $this->getChildHtml('topContainer'); ?>
</div>



