<section class="cart-bottom">
    <div class="page-main">
        <div class="cart-bottom-item cart-bottom-left-container">
            <div class="block block-delivery-returns">
                <div class="block-title">
                    <h3>Delivery FAQ's</h3>
                </div>
                <div class="block-content">
                    <h5>Collect in store or Delivery?</h5>
                    <p>You can opt to have your order delivered or, if you prefer not to pay for delivery, you can collect it from a convenient store that has the required stock available. When you place an item in your basket you will be asked to select either delivery or collect in store. If you opt for delivery the delivery charge will then be added to your basket. If you opt for collect in store you will then be asked to select which store you would like to collect from. The options you choose can also be changed in the final stage of the checkout process should you wish to change your mind.</p>
                </div>
            </div>
        </div>
        <div class="cart-bottom-item cart-bottom-right-container">
            <div class="block block-delivery-returns">
                <div class="block-title">
                    <h3>Returns &amp; Exchanges</h3>
                </div>
                <div class="block-content">
                    <h5>Consumer Guarantees</h5>
                    <p>If you believe an item is faulty, you may have rights to a remedy under the Australian Consumer Law. The Australian Consumer Law does recognise that the relevant time period may vary by product (or service) depending on the nature of the goods (or service), the price paid and any representations made about the goods (or service).</p>
                    <p>Where you believe an item is faulty, it may be necessary for us to send your goods to the manufacturer or their service agent for it to be assessed within a reasonable period of time. If there is a major failure with the item, you may choose a refund, exchange or repair. If the failure is minor, we will repair the item (or, at our discretion, we may replace the item) within a reasonable time.</p>
                </div>
            </div>
        </div>
    </div>
</section>
