<div class="Total-tools-header-for-check-out">
    <div class="header-for-check-out-content">
       <div class="check-out-divine-1">
        <a class="Total-tools-logo-large" href="<?php echo $this->getUrl('') ?>">
            <img width="290" height="57" class="img-responsive" src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="Total-tools-logo-large" /></a>
       </div>
        <div class="check-out-divine-2">
            <div class="check-out-divine-2-wrap">
                <span id="link-in-check-out"><a href='http://127.0.0.1/magento_project/src/index.php/'><</a>
            <a id="go-back-123" href='http://127.0.0.1/magento_project/src/index.php/'>Continue Shopping</a></span>
            <div class="Total-tools-header-minicart">

                <?php echo $this->getChildHtml('minicart_head'); ?>
            </div>
            </div>
        </div>
    </div>
</div>






